name: e_store
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  ## Icons packages
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8



  ## Utility Packages
  http: ^1.1.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  get_storage: ^2.1.1

  ## State management
  
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4

  ## Firebase Packages
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.14.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  ## Product Specific


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  bloc_test: ^9.1.5
  mockito: ^5.4.4


flutter:
  uses-material-design: true
  ## ################ LOCAL Assets ################ ##
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
  
  ## ################ LOCAL Fonts ################ ##
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
