name: e_store
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Icons packages
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  ## Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  connectivity_plus: ^6.0.3
  get_storage: ^2.1.1
  lottie: ^3.1.0

  ## State management

  flutter_bloc: ^8.1.5
  get_it: ^7.7.0

  ## Firebase Packages
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  google_sign_in: ^6.2.1
  # google_sign_in_web: ^0.12.4 //TODO web support

  #Generator Packages
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  ## Product Specific

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  bloc_test: ^9.1.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  ## ################ LOCAL Assets ################ ##
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/

  ## ################ LOCAL Fonts ################ ##
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
